import logging
import re
from urllib.parse import urlparse

from keycloak import KeycloakAdmin, KeycloakOpenIDConnection

from app.core.config import settings

logger = logging.getLogger(__name__)


def _build_customer_client(realm_slug: str) -> dict:
    """Build the docmate-cust client config with redirect URIs for this realm's subdomain."""
    parsed = urlparse(settings.customer_portal_base_url)
    scheme = parsed.scheme or "http"
    host = parsed.hostname or "localhost"
    port = parsed.port

    subdomain_origin = f"{scheme}://{realm_slug}.{host}"
    if port and not (scheme == "http" and port == 80) and not (scheme == "https" and port == 443):
        subdomain_origin += f":{port}"

    dev_uris = [
        "http://localhost:8080/*",
        "http://localhost:5174/*",
    ]
    subdomain_uris = [subdomain_origin, f"{subdomain_origin}/", f"{subdomain_origin}/*"]

    return {
        "clientId": "docmate-cust",
        "name": "DocMate Customer Portal",
        "enabled": True,
        "publicClient": True,
        "bearerOnly": False,
        "consentRequired": False,
        "standardFlowEnabled": True,
        "implicitFlowEnabled": False,
        "directAccessGrantsEnabled": False,
        "serviceAccountsEnabled": False,
        "protocol": "openid-connect",
        "redirectUris": subdomain_uris + dev_uris,
        "webOrigins": ["+"],
        "attributes": {
            "pkce.code.challenge.method": "S256",
            "post.logout.redirect.uris": "##".join(
                [f"{subdomain_origin}/*"] + dev_uris
            ),
        },
    }


DE_REALM = "doc"
DE_CLIENT_ID = "docmate-de"


def _build_de_client() -> dict:
    """Build the docmate-de client config with redirect URIs for every
    configured base URL (settings.de_portal_base_urls, comma-separated)."""
    dev_uris = [
        "http://localhost:5173",
        "http://localhost:5173/",
        "http://localhost:5173/*",
        "http://localhost:80",
        "http://localhost:80/",
        "http://localhost:80/*",
        "http://localhost",
        "http://localhost/",
        "http://localhost/*",
        "http://localhost:8080",
        "http://localhost:8080/",
        "http://localhost:8080/*",
    ]

    base_urls = [u.strip().rstrip("/") for u in settings.de_portal_base_urls.split(",") if u.strip()]
    configured_uris: list[str] = []
    for base_url in base_urls:
        configured_uris += [base_url, f"{base_url}/", f"{base_url}/*"]

    return {
        "clientId": DE_CLIENT_ID,
        "name": "DocMate Digitizing Portal",
        "enabled": True,
        "publicClient": True,
        "bearerOnly": False,
        "consentRequired": False,
        "standardFlowEnabled": True,
        "implicitFlowEnabled": False,
        "directAccessGrantsEnabled": False,
        "serviceAccountsEnabled": False,
        "protocol": "openid-connect",
        "redirectUris": configured_uris + dev_uris,
        "webOrigins": ["+"],
        "attributes": {
            "pkce.code.challenge.method": "S256",
            "post.logout.redirect.uris": "##".join(
                [f"{u}/*" for u in base_urls] + dev_uris
            ),
        },
    }


def sync_de_client() -> None:
    """Idempotently reconcile the docmate-de client's redirect URIs with the
    currently configured DE_PORTAL_BASE_URLS.

    Safe to call on every backend startup: Keycloak's `--import-realm` only
    imports a realm the first time it's seen, so once the realm exists,
    changing hostnames requires this to actually take effect.
    """
    admin = _make_admin("master")
    admin.connection.realm_name = DE_REALM
    clients = admin.get_clients()
    de_client = next((c for c in clients if c["clientId"] == DE_CLIENT_ID), None)
    if not de_client:
        logger.warning("%s client not found in realm %s; skipping redirect URI sync", DE_CLIENT_ID, DE_REALM)
        return
    admin.update_client(de_client["id"], _build_de_client())
    logger.info("Synced redirect URIs for %s client", DE_CLIENT_ID)


CLI_REALM = "doc"
CLI_CLIENT_ID = "docmate-cli"


def _build_cli_client() -> dict:
    """Config for the docmate-cli service-account client (scripts/bulk_upload.py).

    No interactive login, no human credentials — machine-to-machine only.
    Mirrors the same client definition in keycloak/realms/doc-realm.json so
    a fresh import and this idempotent runtime path never drift apart.
    """
    return {
        "clientId": CLI_CLIENT_ID,
        "name": "DocMate Bulk Upload CLI",
        "description": (
            "Service account for scripts/bulk_upload.py — no interactive login, "
            "no human credentials. Secret is auto-generated by Keycloak; "
            "retrieve it via provision_cli_user.py."
        ),
        "enabled": True,
        "publicClient": False,
        "bearerOnly": False,
        "consentRequired": False,
        "standardFlowEnabled": False,
        "implicitFlowEnabled": False,
        "directAccessGrantsEnabled": False,
        "serviceAccountsEnabled": True,
        "protocol": "openid-connect",
    }


def ensure_cli_client() -> str:
    """Idempotently ensure the docmate-cli service-account client exists in the
    doc realm, and return its client secret.

    Handles both cases: the realm was imported fresh with docmate-cli already
    in doc-realm.json (client exists, Keycloak auto-generated a secret at
    import time), and the realm pre-existed before this client was added
    (--import-realm only imports on first realm creation — see
    sync_de_client()'s docstring for the same constraint), in which case the
    client is created here and Keycloak auto-generates the secret then.

    Never rotates an already-existing client's secret — just reads and
    returns its current value, so this is safe to call on every startup or
    provisioning run without invalidating a secret an operator already has.
    """
    admin = _make_admin("master")
    admin.connection.realm_name = CLI_REALM
    clients = admin.get_clients()
    cli_client = next((c for c in clients if c["clientId"] == CLI_CLIENT_ID), None)

    if not cli_client:
        client_uuid = admin.create_client(_build_cli_client(), skip_exists=True)
        if not client_uuid:
            clients = admin.get_clients()
            cli_client = next(c for c in clients if c["clientId"] == CLI_CLIENT_ID)
            client_uuid = cli_client["id"]
        logger.info("Created %s client in realm %s", CLI_CLIENT_ID, CLI_REALM)
    else:
        client_uuid = cli_client["id"]
        # Reconcile config in case it drifted — same idempotent-update pattern
        # as sync_de_client(). Never touches the secret.
        admin.update_client(client_uuid, _build_cli_client())
        logger.info("%s client already exists in realm %s; config reconciled", CLI_CLIENT_ID, CLI_REALM)

    secret_data = admin.get_client_secrets(client_uuid)
    return secret_data["value"]


def slugify(name: str) -> str:
    slug = name.lower()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    return slug.strip("-")[:60]


def _make_admin(realm: str = "master") -> KeycloakAdmin:
    conn = KeycloakOpenIDConnection(
        server_url=settings.keycloak_internal_url.rstrip("/") + "/",
        username=settings.keycloak_admin_user,
        password=settings.keycloak_admin_password,
        realm_name=realm,
        verify=False,
    )
    return KeycloakAdmin(connection=conn)


def create_customer_realm(realm_slug: str, display_name: str) -> None:
    admin = _make_admin("master")
    admin.create_realm(
        {
            "realm": realm_slug,
            "displayName": display_name,
            "enabled": True,
            "registrationAllowed": False,
            "loginWithEmailAllowed": True,
            "otpPolicyType": "totp",
            "otpPolicyAlgorithm": "HmacSHA1",
            "otpPolicyDigits": 6,
            "otpPolicyPeriod": 30,
            "requiredActions": [
                {
                    "alias": "CONFIGURE_TOTP",
                    "name": "Configure OTP",
                    "providerId": "CONFIGURE_TOTP",
                    "enabled": False,
                    "defaultAction": False,
                    "priority": 10,
                    "config": {},
                }
            ],
        },
        skip_exists=True,
    )
    # Create the customer portal client in the new realm
    admin.connection.realm_name = realm_slug
    admin.create_client(_build_customer_client(realm_slug), skip_exists=True)
    logger.info("Provisioned Keycloak realm: %s", realm_slug)


def update_customer_client_uris(realm_slug: str) -> None:
    """Patch an existing realm's docmate-cust client with the current redirect URIs.

    Call this for realms created before the subdomain routing change.
    """
    admin = _make_admin("master")
    admin.connection.realm_name = realm_slug
    clients = admin.get_clients()
    cust_client = next((c for c in clients if c["clientId"] == "docmate-cust"), None)
    if not cust_client:
        logger.warning("docmate-cust client not found in realm %s", realm_slug)
        return
    admin.update_client(cust_client["id"], _build_customer_client(realm_slug))
    logger.info("Updated redirect URIs for realm: %s", realm_slug)


def create_user_in_realm(
    realm_slug: str, email: str, full_name: str, temp_password: str
) -> str:
    """Create user in Keycloak and return the Keycloak UUID (sub claim)."""
    admin = _make_admin("master")
    admin.connection.realm_name = realm_slug

    parts = full_name.split(" ", 1)
    user_id = admin.create_user(
        {
            "username": email,
            "email": email,
            "firstName": parts[0],
            "lastName": parts[1] if len(parts) > 1 else "",
            "enabled": True,
            "emailVerified": True,
            "requiredActions": ["UPDATE_PASSWORD"],
            "credentials": [
                {"type": "password", "value": temp_password, "temporary": True}
            ],
        },
        exist_ok=True,
    )
    return str(user_id)


def set_user_enabled(realm_slug: str, keycloak_sub: str, enabled: bool) -> None:
    admin = _make_admin("master")
    admin.connection.realm_name = realm_slug
    admin.update_user(keycloak_sub, {"enabled": enabled})
